# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_auto_20170726_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='users',
            field=models.ManyToManyField(related_name='lists', to='wish_list.User'),
        ),
    ]
