# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170719_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
