# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0002_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='dojo_secrets.User'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='dojo_secrets.User'),
        ),
    ]
